name: Run unit test

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 22

jobs:
  unit-test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: cd apps/api && npm install

    - name: Unit testing
      run: cd apps/api && npm run test

  unit-test-consumer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
  
    - name: Install Dependencies
      run: cd apps/consumer && npm install

    - name: Unit testing
      run:  cd apps/consumer && npm run test

  unit-test-cleaner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: cd apps/cleaner && npm install

    - name: Unit testing
      run: cd apps/cleaner && npm run test